export const credits = {
  // Must be placed in the order it is desired they appear in the credits
  roles: {
    1: "原版作者",
    2: "模组作者",
    3: "模组汉化者",
    4: "技术工程师",
    5: "领衔开发者",
    6: "移动端开发者",
    7: "Steam 版开发者",
    8: "库开发者",
    9: "开发者",
    10: "模组开发者",
    11: "首席设计顾问",
    12: "设计顾问",
    13: "编剧",
    14: "成就图标设计",
    15: "视觉制作者",
    16: "弹窗设计师、带妹师、厨师",
    17: "地下测试者",
    18: "网页版测试者",
    19: "模组网页端测试者",
    20: "安卓版测试者",
    21: "模组移动端测试者",
    22: "其它贡献者",
  },

  // Each person must have a name and at least one role (the index of the desired role in roles). They can also have a
  // second name, which will appear in parentheses besides their first.
  people: [
    { name: "Hevipelle", name2: "Ivar Kerajärvi", roles: 1 },
    { name: "Supersonic Seven", name2: "Benjamin Rockholz", roles: 2 },
    { name: "松茸不吃柯尔鸭", name2: "mushduck(qq:3151643233)", roles: 3 },
    { name: "Razenpok", name2: "Andrei Andreev", roles: 4 },
    { name: "garnet420", roles: 5 },
    { name: "Omsi", roles: [5, 14] },
    { name: "SpectralFlame", name2: "Christopher Yip", roles: 5 },
    { name: "WaitingIdly", roles: [5, 9, 12, 18, 20] },
    { name: "kajfik", name2: "Jakub Kajfosz", roles: 6 },
    { name: "Makopaz", name2: "Zack Stein", roles: 7 },
    { name: "Patashu", roles: [8, 9, 18] },
    { name: "Dan", roles: [9, 18] },
    { name: "earth", name2: "Jace Royer", roles: [9, 16, 18, 20] },
    { name: "Hira", roles: [9, 18, 20] },
    { name: "IkerStream", name2: "Iker de Aguirre", roles: [9, 18] },
    { name: "L4R5", name2: "Lars Wolf", roles: [9, 18, 20] },
    { name: "Pichusuperlover", roles: [9, 12, 18] },
    { name: "realrapidjazz", roles: [9, 11, 13] },
    { name: "Scarlet", roles: [9, 18, 20] },
    { name: "slabdrill", roles: 9 },
    { name: "Didgoty", roles: [10, 19, 22] },
    { name: "Living_Person", name2: "Life", roles: [10, 19, 22] },
    { name: "Qwerty", roles: [10, 19, 22] },
    { name: "Acamaeda", roles: [12, 18] },
    { name: "epic_ducks", name2: "Elys", roles: [14, 19, 22] },
    { name: "Spoofy", roles: 15 },
    { name: "Dravitar", name2: "Alex Henderson", roles: 17 },
    { name: "Aesis", roles: 18 },
    { name: "AFYINEE", name2: "Gabriel HADDAG", roles: 18 },
    { name: "Alexitato", roles: 18 },
    { name: "Anno", roles: 18 },
    { name: "Myresa Exina", roles: [18, 20] },
    { name: "ArrowBounce", name2: "Timothy Su", roles: 18 },
    { name: "Birb", name2: "Kelsey Black", roles: 18 },
    { name: "Boo", name2: "Jean-Christophe Bourgault", roles: 18 },
    { name: "CaptainGalaxy", name2: "Ovidijus Točelis", roles: 18 },
    { name: "ChaoticHans", roles: [18, 20] },
    { name: "cubic frog", roles: 18 },
    { name: "dankesehr", roles: 18 },
    { name: "Davixx", name2: "Davide Fedele", roles: 18 },
    { name: "Empireus", roles: 18 },
    { name: "GirixK", name2: "Nikola Jelinčić", roles: [18, 20] },
    { name: "GoldenTritium", roles: [18, 20] },
    { name: "Kael", roles: 18 },
    { name: "Lynn", roles: 18 },
    { name: "Merp", roles: 18 },
    { name: "philipebreaker", name2: "Philipe", roles: 18 },
    { name: "Phillip Marshall", roles: 18 },
    { name: "Phoebe", roles: 18 },
    { name: "Reda Kotob", roles: 18 },
    { name: "Saturnus", roles: [18, 13] },
    { name: "SereKabii", roles: 18 },
    { name: "Sheer", roles: 18 },
    { name: "sirusi", name2: "Vinícius Oliveira Martins", roles: 18 },
    { name: "Spanosa", name2: "Jared K", roles: 18 },
    { name: "Sparticle999", roles: 18 },
    { name: "SpicyCrusader13", roles: [18, 20] },
    { name: "Storm", roles: 18 },
    { name: "SzyszakS", roles: 18 },
    { name: "Tacitus", roles: 18 },
    { name: "Typh", roles: 18 },
    { name: "Vnge", name2: "Ben Parrish", roles: [18, 20] },
    { name: "Xemadus", name2: "Jonathan Gibson", roles: 18 },
    { name: "Young Woo Joo", roles: 18 },
    { name: "Zipi", roles: 18 },
    { name: "AKA", roles: 19 },
    { name: "ape", roles: 19 },
    { name: "AutismQueen", roles: [19, 22] },
    { name: "Blast2026", roles: [19, 22] },
    { name: "Calm Carrot", roles: 19 },
    { name: "dark fox", roles: 19 },
    { name: "DavTheGl1tchyOne", roles: 19 },
    { name: "Deadly", roles: 19 },
    { name: "enitiaty", roles: 19 },
    { name: "Error404", roles: [19, 22] },
    { name: "glitchy", roles: [19, 22] },
    { name: "hz", roles: 19 },
    { name: "iliketrains123_no", roles: 19 },
    { name: "Josearthu", roles: 19 },
    { name: "M3t0s1m", roles: 19 },
    { name: "MagolorGamerJC", roles: 19 },
    { name: "MidnightLight", name2: "Midnight", roles: 19 },
    { name: "misc", roles: 19 },
    { name: "Quantaum", roles: 19 },
    { name: "Redshift_Shine", roles: 19 },
    { name: "Riley", roles: 19 },
    { name: "S____", roles: [19, 22] },
    { name: "spinfish96", roles: 19 },
    { name: "Sumi", name2: "Lilly", roles: [19, 22] },
    { name: "SwordPunk", roles: 19 },
    { name: "realmatryx", name2: "Matthew", roles: [19, 22] },
    { name: "about:blank", roles: 20 },
    { name: "ÆiOuF", roles: 20 },
    { name: "Akirious", roles: 20 },
    { name: "Anjinho01", roles: 20 },
    { name: "Anthios", roles: 20 },
    { name: "Aubrey Ark", roles: 20 },
    { name: "Auti", name2: "Lucia Tolle", roles: 20 },
    { name: "Buck", roles: 20 },
    { name: "Barrin84", roles: [20, 21] },
    { name: "Calmcat", roles: 20 },
    { name: "ChizuX", roles: 20 },
    { name: "Circle", roles: 20 },
    { name: "Crinkly Weasel", name2: "Aaryan Sarawgi", roles: 20 },
    { name: "Daniella", roles: 20 },
    { name: "DarthDie", name2: "Briar Bowser", roles: 20 },
    { name: "ElPopote83", roles: 20 },
    { name: "Epsilon", name2: "Coolguystorm", roles: 20 },
    { name: "Firecracker", roles: 20 },
    { name: "Gaunter", roles: 20 },
    { name: "Gimmick", roles: 20 },
    { name: "HarrisL2", roles: 20 },
    { name: "Hellbach", name2: "Asher Günther", roles: 20 },
    { name: "hen-ben", name2: "Henry Ellenberg", roles: 20 },
    { name: "ImpossibleSalsa", roles: 20 },
    { name: "JayM#1872", name2: "Jay McGee", roles: 20 },
    { name: "Johanniklas", name2: "Jan-Niklas Petersen", roles: 20 },
    { name: "Joseph Micheli", roles: 20 },
    { name: "kaislash", name2: "Lily", roles: 20 },
    { name: "Kirku", name2: "Fabian Makowski", roles: 20 },
    { name: "Kirin", name2: "Arthur", roles: 20 },
    { name: "Klötzchen", roles: 20 },
    { name: "L5racer", roles: 20 },
    { name: "Marshmallow", roles: 20 },
    { name: "HyperionMike", name2: "Miikael Siitan", roles: 20 },
    { name: "Mirai", roles: 20 },
    { name: "Monoma", name2: "ARoman Ruiz", roles: 20 },
    { name: "Nani", roles: 20 },
    { name: "Neo", name2: "Joon", roles: 20 },
    { name: "netweak", roles: 20 },
    { name: "NiZeKiHo", name2: "Nica", roles: 20 },
    { name: "NotBrewst", name2: "Luc Leblanc", roles: 20 },
    { name: "opdollar", name2: "Zane Coole", roles: 20 },
    { name: "Pavlxiiv", roles: 20 },
    { name: "coffeeflake", roles: 20 },
    { name: "Razor", roles: 20 },
    { name: "Razvan Cercel", roles: 20 },
    { name: "ReacTivity", roles: 20 },
    { name: "Reaxt", name2: "Rea Koehler", roles: 20 },
    { name: "Ruins", roles: 20 },
    { name: "Rukimix", roles: 20 },
    { name: "shadowevil", roles: 20 },
    { name: "Skunky", name2: "Lukas", roles: 20 },
    { name: "Snaeky", roles: 20 },
    { name: "Socks", name2: "Hannah Pocks", roles: 20 },
    { name: "Sweets the Alien", roles: 20 },
    { name: "Tables", roles: 20 },
    { name: "Taylor Reeves", roles: 20 },
    { name: "TheAhmex", roles: 20 },
    { name: "The Trust Melon", roles: 20 },
    { name: "Tim Wong", roles: 20 },
    { name: "tragedt", name2: "Ethan Manninen", roles: 20 },
    { name: "tui sapo", roles: 20 },
    { name: "Valentine Clarissa Alanis Star Z", roles: 20 },
    { name: "vanadium_void", roles: 20 },
    { name: "X3N0_32", roles: 20 },
    { name: "ZylaKat", name2: "Katherine Goforth-Harbin", roles: 20 },
    { name: "Jedall", roles: 20 },
    { name: "Lapis", roles: 20 },
    { name: "Guimora", roles: 20 },
    { name: "Neowo", name2: "Neo Mitchell", roles: 20 },
    { name: "AshTheDinosaur", roles: 20 },
    { name: "Annyeong1", name2: "Jeeho Yoon", roles: 20 },
    { name: "Dedzuka", roles: 20 },
    { name: "Something", name2: "Sushi", roles: 20 },
    { name: "Viola", roles: 20 },
    { name: "Luna van Yeethoven", roles: 20 },
    { name: "Lotocion", roles: 20 },
    { name: "Merlyn", roles: 20 },
    { name: "Tilly", roles: 20 },
    { name: "Sauer", name2: "Matt", roles: 20 },
    { name: "PtigaD", roles: 20 },
    { name: "Aleame", roles: 20 },
    { name: "GFADE00", roles: 20 },
    { name: "Amity Emily", roles: 20 },
    { name: "BsonHK", roles: 20 },
    { name: "Angel", roles: 20 },
    { name: "OhBrod", roles: 20 },
    { name: "sxy62146214", roles: 20 },
    { name: "cyxw", roles: 20 },
    { name: "Cosmic_Fyre", roles: 20 },
    { name: "The Cube Dude", roles: 20 },
    { name: "Tias", name2: "Tim Stanglow", roles: 20 },
    { name: "Rad Cooldude", roles: 20 },
    { name: "DataBitMC", roles: 20 },
    { name: "Pizzalover04", name2: "Zanpaulco", roles: 20 },
    { name: "Airakogi", roles: 20 },
    { name: "Boney_joe", roles: 22 },
    { name: "Creepmond", name2: "Creep", roles: 22 },
    { name: "Gigachad45", roles: 22 },
    { name: "Tojo", roles: 22 }
  ]
};

credits.roles.count = Object.keys(credits.roles).length;